## Tesnor数据类型 （张量）
0维：点，标量  
1维：向量  
2维：矩阵  
多维：多维矩阵  

In [10]:
import torch 

In [11]:
# 1.1 标量
a = torch.tensor(1)
print(type(a))
print(a)
print(a.size())

<class 'torch.Tensor'>
tensor(1)
torch.Size([])


In [15]:
# 1.2 向量
b = torch.tensor([1])
print(type(b))
print(b)
print(b.size())

b1 = torch.tensor([1,2,3])

print(type(b1))
print(b1)
print(b1.size())

<class 'torch.Tensor'>
tensor([1])
torch.Size([1])
<class 'torch.Tensor'>
tensor([1, 2, 3])
torch.Size([3])


In [13]:
# 1.3 矩阵
c = torch.tensor([
    [1, 2],
    [3, 4]]
)
print(type(c))
print(c)
print(c.size())

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [14]:
# 1.4 多维矩阵
d = torch.tensor([
    [
        [1, 2], [1, 2],
        [1, 2], [1, 2]
    ],
    [
        [1, 2], [1, 2],
        [1, 2], [1, 2]
    ],
    [
        [1, 2], [1, 2],
        [1, 2], [1, 2]
    ]
])
print(type(d))
print(d)
print(d.size())

<class 'torch.Tensor'>
tensor([[[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]],

        [[1, 2],
         [1, 2],
         [1, 2],
         [1, 2]]])
torch.Size([3, 4, 2])
