In [1]:
import torch 

### 1 矩阵的转置 

In [8]:
a = torch.tensor([[1.0,2],[3,4]])

In [9]:
a

tensor([[1., 2.],
        [3., 4.]])

In [10]:
a.transpose(1,0)

tensor([[1., 3.],
        [2., 4.]])

In [11]:
a.transpose(0,1)

tensor([[1., 3.],
        [2., 4.]])

### 2 矩阵的逆

In [12]:
torch.inverse(a)

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

## 3 矩阵的秩

In [13]:
torch.matrix_rank(a)

tensor(2)

### 4 矩阵的迹 

In [14]:
torch.trace(a)

tensor(5.)

### 5 矩阵的行列式 

In [15]:
torch.det(a)

tensor(-2.0000)

## 6 矩阵的特征值和特征向量 

In [17]:
torch.eig(a,eigenvectors=True)

torch.return_types.eig(
eigenvalues=tensor([[-0.3723,  0.0000],
        [ 5.3723,  0.0000]]),
eigenvectors=tensor([[-0.8246, -0.4160],
        [ 0.5658, -0.9094]]))