### 1 四则运算：加减乘除
torch.add(input, alpha=1, other, out=None)  
torch.addcdiv(tensor, value=1, tensor1, tensor2, out=None)  
torch.addcmul(tensor, value=1, tensor1, tensor2, out=None)  
torch.sub(input, other, out=None)  
torch.mul(input, other, out=None)  
torch.div(input, other, out=None)  


In [1]:
import torch

In [3]:
a = torch.rand(3,4)
b = torch.rand(3,4)
print(a)
print(b)

tensor([[0.6585, 0.5872, 0.1523, 0.6315],
        [0.8839, 0.2742, 0.5890, 0.5073],
        [0.9062, 0.5147, 0.4520, 0.7539]])
tensor([[0.1982, 0.7813, 0.2600, 0.0372],
        [0.0693, 0.2151, 0.2451, 0.2351],
        [0.0554, 0.3463, 0.8022, 0.6366]])


In [4]:
torch.add(a,b)

tensor([[0.8567, 1.3685, 0.4122, 0.6687],
        [0.9532, 0.4894, 0.8341, 0.7424],
        [0.9616, 0.8609, 1.2543, 1.3906]])

In [12]:
torch.addcdiv(torch.rand(3,4),a,b)

tensor([[ 3.3524,  1.7254,  1.1657, 17.5210],
        [13.7119,  1.5031,  2.6063,  2.8464],
        [16.5303,  2.1327,  1.4472,  1.2102]])

In [13]:
torch.sub(a,b)

tensor([[ 0.4602, -0.1941, -0.1077,  0.5944],
        [ 0.8146,  0.0591,  0.3439,  0.2722],
        [ 0.8508,  0.1684, -0.3502,  0.1173]])

In [14]:
torch.mul(a,b)

tensor([[0.1305, 0.4588, 0.0396, 0.0235],
        [0.0612, 0.0590, 0.1444, 0.1193],
        [0.0502, 0.1782, 0.3626, 0.4800]])

In [19]:
torch.mul(a,2)

tensor([[1.3170, 1.1744, 0.3045, 1.2631],
        [1.7678, 0.5485, 1.1780, 1.0146],
        [1.8125, 1.0293, 0.9040, 1.5079]])

In [21]:
torch.div(a,1)

tensor([[0.6585, 0.5872, 0.1523, 0.6315],
        [0.8839, 0.2742, 0.5890, 0.5073],
        [0.9062, 0.5147, 0.4520, 0.7539]])

### 2 对数，指数，幂函数运算
torch.log()  
torch.log10()  
torch.log2()  
torch.exp()  
torch.pow()  

In [34]:
x = torch.tensor([3.0,4.0])

In [35]:
x

tensor([3., 4.])

In [36]:
torch.log(x)

tensor([1.0986, 1.3863])

In [37]:
torch.log10(x)

tensor([0.4771, 0.6021])

In [38]:
torch.log2(x)

tensor([1.5850, 2.0000])

In [43]:
torch.exp(x)

tensor([20.0855, 54.5981])

In [42]:
torch.pow(x,2)

tensor([ 9., 16.])

### 3 三角函数计算

In [51]:
torch.sin(torch.tensor([3.1515926/2]))

tensor([1.0000])

In [54]:
torch.cos(torch.tensor([0.0]))

tensor([1.])

In [57]:
torch.tan(torch.tensor([0.0]))

tensor([0.])