### 1 pytorch中的自动微分  
pytorch实现了因变量对一系列自变量的自动求导，应用在神经网络的链式法则。

### 2 自动微分举例  

In [158]:
import torch

### 2.1 简单的自动微分：标量
如果Tensor类表示的是一个标量，则不需要为backward()指定任何参数。   
但是如果它有更多的元素，则需要指定一个gradient参数，它是形状匹配的张量。   

In [159]:
w = torch.tensor(3.0,requires_grad=True)
x = torch.tensor(5.0,requires_grad=True)
b = torch.tensor(10.0,requires_grad=True)

In [160]:
z = w*x+b

In [161]:
z.backward()

In [162]:
print(x.grad.data)  
print(w.grad.data)
print(b.grad.data)

tensor(3.)
tensor(5.)
tensor(1.)


### 2.1 复杂的自动微分：向量或者更多维tensor

In [163]:
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [164]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [165]:
print(x.is_leaf)
print(y.is_leaf)

True
False


In [166]:
z=y*y*3
out=z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [167]:
out.backward()

In [168]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [172]:
x = torch.tensor([1.0,2,3,4],requires_grad=True)
y=2*x
z=y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [173]:
v=torch.tensor([[1.0,1],[1,1]],requires_grad=True)
z.backward(v)
print(x.grad)

tensor([2., 2., 2., 2.])
