## pytorch中创建张量的函数  
更多创建张量的方法参考：https://pytorch.org/docs/stable/tensors.html

In [21]:
import torch 

### 1 创建张量的方法举例 

In [22]:
# 1 创建全0张量
x_zeros = torch.zeros((3, 3))
print(x_zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [23]:
# 2 创建全1张量
x_ones = torch.ones((3, 3))
print(x_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [24]:
# 3 随机创建张量-均匀分布[0,1)
for i in range(5):
    x_rand = torch.rand((3, 3))
    print(x_rand)

tensor([[0.8457, 0.9946, 0.0546],
        [0.4997, 0.3072, 0.3124],
        [0.7492, 0.0874, 0.6146]])
tensor([[0.1502, 0.7328, 0.7626],
        [0.2934, 0.4336, 0.7766],
        [0.2727, 0.9342, 0.3673]])
tensor([[0.1938, 0.7106, 0.4193],
        [0.0067, 0.3246, 0.5228],
        [0.0732, 0.7138, 0.3520]])
tensor([[0.1514, 0.4334, 0.2650],
        [0.5948, 0.7525, 0.2161],
        [0.1625, 0.4575, 0.5656]])
tensor([[0.2582, 0.2364, 0.1756],
        [0.2396, 0.9150, 0.9401],
        [0.1849, 0.6766, 0.9486]])


In [25]:
# 4 随机创建张量-标准正态分布
for i in range(5):
    x_randn = torch.randn((3, 3))
    print(x_randn)

tensor([[-0.0418, -0.1411, -0.8181],
        [-0.6138, -1.1927,  0.2212],
        [ 0.0518,  0.3459,  1.2211]])
tensor([[-0.3250, -1.6226,  1.7400],
        [ 1.7518,  0.1909, -0.0632],
        [ 1.2392, -0.0207,  2.0002]])
tensor([[-1.6730,  0.7898, -0.7678],
        [-1.5474,  0.0367, -1.2842],
        [-1.1684, -0.5605, -0.2899]])
tensor([[ 0.3534, -1.5259, -0.6579],
        [ 1.2599, -0.5789, -0.1751],
        [ 0.4161, -0.3161, -1.3250]])
tensor([[-0.7926, -0.8082, -0.7152],
        [ 1.6350,  0.3823, -1.2431],
        [ 0.1808, -0.9741,  0.1143]])


In [26]:
# 5 随机创建张量-均匀分布 指定范围的整数
for i in range(5):
    x_randi = torch.randint(10, (3, 3))
    print(x_randi)

tensor([[9, 9, 2],
        [3, 0, 7],
        [7, 2, 4]])
tensor([[1, 1, 7],
        [7, 1, 3],
        [1, 2, 0]])
tensor([[6, 0, 0],
        [8, 5, 8],
        [2, 8, 0]])
tensor([[9, 3, 3],
        [1, 7, 7],
        [4, 4, 2]])
tensor([[1, 4, 3],
        [7, 0, 7],
        [4, 0, 6]])


### 2 Tensor类型与numpy数据类型的转换
numpy的更多内容参考：https://numpy.org/devdocs/user/quickstart.html  

In [27]:
# numpy 转tensor
import numpy as np 
x_np = np.array([[1, 2], [3, 4]])
x_tensor = torch.from_numpy(x_np)
print(x_np)
print(x_tensor)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [28]:
# tensor转numpy 
x_np_ = x_tensor.numpy()
print(x_np_)

[[1 2]
 [3 4]]
