### 1 参数初始化
init模块位置：torch.nn包中，from torch.nn import init  
官网：https://pytorch.org/docs/stable/nn.init.html   

### 2 初始化方法介绍 

In [4]:

from torch.nn import init
import torch

w = torch.empty(3, 3)

uniform = init.uniform_(w)
print(uniform)

# 1 
normal = init.normal_(w)
print(normal)

# 2 
constant = init.constant_(w, 2.0)
print(normal)

# 3  
eye = init.eye_(w)
print(eye)

# 4   
w_ = torch.empty(3, 16, 5, 5)
dirac = init.dirac_(w_)
print(dirac)

# 5 
xavier_uniform = init.xavier_uniform_(w)
print(xavier_uniform)

# 6   
xavier_normal = init.xavier_normal_(w)
print(xavier_normal)

# 7    
kaiming_uniform = init.kaiming_uniform_(w)
print(kaiming_uniform)

# 8   
kaiming_normal = init.kaiming_normal_(w)
print(kaiming_uniform)

# 9   
orthogonal = init.orthogonal_(w)
print(orthogonal)

# 10    
sparse = init.sparse_(w, sparsity=0.2)
print(sparse)


tensor([[0.5307, 0.0723, 0.6085],
        [0.7549, 0.7602, 0.1009],
        [0.2672, 0.6473, 0.4489]])
tensor([[ 0.4678,  0.5975,  1.5908],
        [-0.5945,  0.5869,  0.2804],
        [ 0.7934, -1.1040, -0.0996]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         ...,

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0.,