### 1 删除维度为1的维度：torch.squeeze()

In [11]:
import torch

In [18]:
a = torch.rand(3,1,1,6)

In [19]:
a.size()

torch.Size([3, 1, 1, 6])

In [20]:
b = torch.squeeze(a)
b.size()

torch.Size([3, 6])

In [21]:
b

tensor([[0.7602, 0.4312, 0.1838, 0.3196, 0.1801, 0.7492],
        [0.3767, 0.7051, 0.2068, 0.8815, 0.3442, 0.2890],
        [0.8634, 0.4648, 0.5061, 0.5898, 0.8630, 0.9634]])

### 2 在指定位置插入维度为1的维度:torch.unsqueeze()

In [22]:
x=torch.rand(3,3)

In [25]:
x.size()

torch.Size([3, 3])

In [30]:
y = torch.unsqueeze(x,2)

In [31]:
y.size()

torch.Size([3, 3, 1])

### 3 在指定维度上对张量进行拼接操作 :torch.cat

In [44]:
x1 = torch.rand(3,3)
x2 = torch.rand(3,3) 

x = torch.cat((x1,x2),1)
y = torch.cat((x1,x2),0)

In [45]:
x1

tensor([[0.4465, 0.6883, 0.6064],
        [0.6696, 0.1908, 0.4945],
        [0.8652, 0.4769, 0.7449]])

In [46]:
x2

tensor([[0.4501, 0.1678, 0.3242],
        [0.9911, 0.9107, 0.3461],
        [0.4288, 0.2735, 0.8026]])

In [47]:
x

tensor([[0.4465, 0.6883, 0.6064, 0.4501, 0.1678, 0.3242],
        [0.6696, 0.1908, 0.4945, 0.9911, 0.9107, 0.3461],
        [0.8652, 0.4769, 0.7449, 0.4288, 0.2735, 0.8026]])

In [48]:
y

tensor([[0.4465, 0.6883, 0.6064],
        [0.6696, 0.1908, 0.4945],
        [0.8652, 0.4769, 0.7449],
        [0.4501, 0.1678, 0.3242],
        [0.9911, 0.9107, 0.3461],
        [0.4288, 0.2735, 0.8026]])

### 4 对张量进行变形操作 

In [49]:
x = torch.rand(24)

In [50]:
x.view(4,6)

tensor([[0.9242, 0.9486, 0.0778, 0.3955, 0.4541, 0.9230],
        [0.4422, 0.5327, 0.0753, 0.1761, 0.4588, 0.4054],
        [0.5887, 0.3625, 0.2744, 0.1909, 0.0919, 0.3794],
        [0.8572, 0.3379, 0.7439, 0.0581, 0.9429, 0.0718]])

x.view(2,3,4)

### 5 增加新的维度进行堆叠:torch.stack

In [86]:
x1= torch.rand(3,3)
x2= torch.rand(3,3)

In [87]:
x = torch.stack((x1,x2),0)
y = torch.stack((x1,x2),1)
z = torch.stack((x1,x2),2)

In [88]:
x1.size()

torch.Size([3, 3])

In [89]:
x2.size()

torch.Size([3, 3])

In [90]:
x.size()

torch.Size([2, 3, 3])

In [91]:
y.size()

torch.Size([3, 2, 3])

In [92]:
z.size()

torch.Size([3, 3, 2])

### 6 交换维度

In [97]:
x= torch.rand(3,3,4,2)
x

tensor([[[[0.9324, 0.2136],
          [0.8151, 0.9263],
          [0.0643, 0.4161],
          [0.6478, 0.6522]],

         [[0.1823, 0.1293],
          [0.1496, 0.4427],
          [0.5730, 0.1683],
          [0.1251, 0.6011]],

         [[0.2152, 0.3298],
          [0.8383, 0.4119],
          [0.5483, 0.1983],
          [0.7122, 0.3095]]],


        [[[0.4071, 0.7896],
          [0.7533, 0.0877],
          [0.9219, 0.2411],
          [0.3678, 0.2430]],

         [[0.4965, 0.3026],
          [0.8523, 0.9061],
          [0.6938, 0.0257],
          [0.4804, 0.1263]],

         [[0.8641, 0.0049],
          [0.5663, 0.6971],
          [0.8994, 0.2432],
          [0.3777, 0.4181]]],


        [[[0.8028, 0.5148],
          [0.1527, 0.2548],
          [0.7785, 0.6627],
          [0.2134, 0.8163]],

         [[0.7922, 0.0703],
          [0.6822, 0.7359],
          [0.4362, 0.2421],
          [0.4697, 0.5187]],

         [[0.6317, 0.9229],
          [0.2919, 0.2319],
          [0.5160, 0.7146],


In [98]:
x.permute(1,0,3,2)

tensor([[[[0.9324, 0.8151, 0.0643, 0.6478],
          [0.2136, 0.9263, 0.4161, 0.6522]],

         [[0.4071, 0.7533, 0.9219, 0.3678],
          [0.7896, 0.0877, 0.2411, 0.2430]],

         [[0.8028, 0.1527, 0.7785, 0.2134],
          [0.5148, 0.2548, 0.6627, 0.8163]]],


        [[[0.1823, 0.1496, 0.5730, 0.1251],
          [0.1293, 0.4427, 0.1683, 0.6011]],

         [[0.4965, 0.8523, 0.6938, 0.4804],
          [0.3026, 0.9061, 0.0257, 0.1263]],

         [[0.7922, 0.6822, 0.4362, 0.4697],
          [0.0703, 0.7359, 0.2421, 0.5187]]],


        [[[0.2152, 0.8383, 0.5483, 0.7122],
          [0.3298, 0.4119, 0.1983, 0.3095]],

         [[0.8641, 0.5663, 0.8994, 0.3777],
          [0.0049, 0.6971, 0.2432, 0.4181]],

         [[0.6317, 0.2919, 0.5160, 0.3768],
          [0.9229, 0.2319, 0.7146, 0.8212]]]])